apiVersion: apps/v1
kind: Deployment
metadata:
  name: system-info-service
  labels:
    app: system-info-service
  namespace: system-info-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: system-info-service
  template:
    metadata:
      labels:
        app: system-info-service
    spec:
      containers:
      - name: system-info
        image: inspiremirnal/system-info:1.0.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        # Pod information
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: POD_UID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
        # Node information
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: CONTAINER_CPU_REQUEST
          valueFrom:
              resourceFieldRef:
                containerName: system-info
                resource: requests.cpu
        - name: CONTAINER_MEMORY_REQUEST
          valueFrom:
              resourceFieldRef:
                containerName: system-info
                resource: requests.memory
        # Container information
        - name: CONTAINER_NAME
          value: "system-info"
        - name: CONTAINER_IMAGE
          value: "system-info:1.0.0"
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        readinessProbe:
          httpGet:
            path: /health/local
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/local
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
